### ISSUE TITLE
some users get ignored on rating changes

### ISSUE THREAD

**Issue by victorsenam** [maratonime/contestwatcher#33]

**Comment by victorsenam** [comment]
@gabrielrussoc said there's a limit for requests on codeforces Api. Now it's only a bug, not a question.

**Comment by gabrielrussoc** [comment]
here we get all the handles from the cf api call, which are exactly as in the website (with capital letters)
https://github.com/maratonime/contestwatcher/blob/548aec49ff000bed366f9effa0618981fa1f8450/fetchers/codeforces.js#L47

and here we compare them to the handles in our database (which are being lowercased - done by #26 )
https://github.com/maratonime/contestwatcher/blob/548aec49ff000bed366f9effa0618981fa1f8450/fetchers/codeforces.js#L56

**Comment by victorsenam** [comment]
Old handles are still now lowercased, right? We can let them break, we can manually lowercase the whole database (sounds reasonable) or we should check if there's some case insensitive version of "has" (unlikely).

**Comment by gabrielrussoc** [comment]
We could change the database but we can always just lowercase whenever we need to compare them.

**Comment by victorsenam** [comment]
One solution removes the need for the other. But if you wanna do it I don't mind.

**Comment by gabrielrussoc** [comment]
i like yours go ahead

**Comment by victorsenam** [comment]
Tasks pending:
- [ ] Fix db by lowercasing old entries
- [ ] Lowercase api handles for comparsion

**Comment by victorsenam** [comment]
Supposed to be fixed, closing issue for now

**Comment by gabrielrussoc** [comment]
as noted in #37, we are assuming the handles are lowercased on the database, but they are not

**Comment by mikaelmello** [comment]
Confirming that it is working now, all handles were correctly displayed in the last round (964)
